# Sponsorship links for the "Sponsor" button on the repo.
# Uncomment / edit as needed. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [jsonnguyen19]
# ko_fi: sonsery
# custom: ["https://flow.sonsery.online/"]
