"""Cross-platform helpers for SSH askpass.

Holds ALL the OS-specific logic (keyring lookup, helper script content,
chmod executable, file permission warnings). The facade `runctx.utils.askpass`
keeps the public API + concrete file paths, and delegates down here.

Pattern: public function = pure dispatcher, private function =
`_<action>_<subject>_<platform>`.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

from .system import current_os, is_windows

# Keyring entry name (gnome-keyring / macOS Keychain).
KEYRING_SERVICE = "ssh"
KEYRING_KEY = "github"

# Keyring subprocess timeout (seconds).
_KEYRING_TIMEOUT = 3


# ============ KEYRING (dispatcher) ============


def _get_keyring_linux() -> str | None:
    """Read from secret-tool (gnome-keyring). Returns None if unavailable."""
    if not shutil.which("secret-tool"):
        return None
    try:
        proc = subprocess.run(
            ["secret-tool", "lookup", "service", KEYRING_SERVICE, "key", KEYRING_KEY],
            capture_output=True,
            text=True,
            timeout=_KEYRING_TIMEOUT,
        )
        if proc.returncode == 0:
            return proc.stdout.strip() or None
        return None
    except Exception:
        return None


def _get_keyring_macos() -> str | None:
    """Read from security find-generic-password (Keychain). Returns None if unavailable."""
    if not shutil.which("security"):
        return None
    try:
        proc = subprocess.run(
            [
                "security",
                "find-generic-password",
                "-s",
                KEYRING_SERVICE,
                "-a",
                KEYRING_KEY,
                "-w",
            ],
            capture_output=True,
            text=True,
            timeout=_KEYRING_TIMEOUT,
        )
        if proc.returncode == 0:
            return proc.stdout.strip() or None
        return None
    except Exception:
        return None


def _get_keyring_windows() -> str | None:
    """Windows has no standard keyring CLI; fall back to file/env sources."""
    return None


_KEYRING_BY_OS = {
    "Linux": _get_keyring_linux,
    "Darwin": _get_keyring_macos,
    "Windows": _get_keyring_windows,
}


def get_keyring() -> str | None:
    """Get passphrase from system keyring by OS. Unknown OS -> None."""
    keyring_source = _KEYRING_BY_OS.get(current_os())
    return keyring_source() if keyring_source is not None else None


# ============ FILE PERMISSION WARNING (dispatcher) ============


def _warn_file_permission_posix(path: Path) -> None:
    """Warn if file permissions are too open (not 600)."""
    mode = path.stat().st_mode & 0o777
    if mode & 0o077:
        print(
            f"WARN: {path} has permissions {oct(mode)} (should be 0o600). Run: chmod 600 {path}",
            file=sys.stderr,
        )


def _warn_file_permission_windows(path: Path) -> None:
    """Windows has no POSIX permissions -> no-op."""
    return


def warn_file_permission(path: Path) -> None:
    """Warn about file permissions on POSIX. Windows: no-op."""
    if is_windows():
        _warn_file_permission_windows(path)
    else:
        _warn_file_permission_posix(path)


# ============ HELPER SCRIPT CONTENT (dispatcher) ============

_HELPER_CONTENT_POSIX = """#!/bin/sh
# Auto-generated by runctx.utils.askpass. Do not edit manually.
# ssh calls this script when no TTY is available to fetch the passphrase.
exec "{python}" -m runctx.utils.askpass "$@"
"""

_HELPER_CONTENT_WINDOWS = """@echo off
"{python}" -m runctx.utils.askpass %*
"""


def _helper_content_windows(python: str) -> str:
    return _HELPER_CONTENT_WINDOWS.format(python=python)


def _helper_content_posix(python: str) -> str:
    return _HELPER_CONTENT_POSIX.format(python=python)


def helper_content(python: str | None = None) -> str:
    """Helper script content by OS. python=None -> use sys.executable."""
    if python is None:
        python = sys.executable or "python3"
    if is_windows():
        return _helper_content_windows(python)
    return _helper_content_posix(python)


# ============ HELPER EXECUTABLE (dispatcher) ============


def _chmod_executable_posix(path: Path) -> None:
    path.chmod(0o700)


def _chmod_executable_windows(path: Path) -> None:
    """Windows does not need chmod."""
    return


def chmod_executable(path: Path) -> None:
    """Make helper executable on POSIX. Windows: no-op."""
    if is_windows():
        _chmod_executable_windows(path)
    else:
        _chmod_executable_posix(path)
