#!/usr/bin/env python3
"""Sync prompts from prompts/*.txt to runctx-extension/popup/prompts.js

Each prompts/<name>.txt file is emitted as a JS const (<NAME>_CONTENT)
exposed on window. Whatever *.txt is present in prompts/ is what ships.
Format: const <NAME>_CONTENT = `...`;
"""

import shutil
import sys
from pathlib import Path


def read_prompt_file(filepath):
    """Read prompt file and escape for JavaScript template literal"""
    with open(filepath, encoding="utf-8") as f:
        content = f.read()
    # Remove file header comments (lines starting with #)
    lines = content.split("\n")
    cleaned_lines = []
    for line in lines:
        if line.strip().startswith("#") and not line.strip().startswith("##"):
            continue
        cleaned_lines.append(line)
    content = "\n".join(cleaned_lines).strip()
    # Escape for template literal
    content = content.replace("\\", "\\\\")
    content = content.replace("`", "\\`")
    content = content.replace("${", "\\${")
    return content


PROMPT_NAMES = [
    "agentctx",
]

# Map prompt name -> JS const name
CONST_NAMES = {
    "agentctx": "AGENTCTX_CONTENT",
}


def main():
    script_dir = Path(__file__).resolve().parent
    prompts_dir = script_dir / "prompts"
    prompts_js = script_dir / "runctx-extension" / "popup" / "prompts.js"

    print(f"📁 Syncing prompts from {prompts_dir} to {prompts_js}...")

    if not prompts_dir.exists():
        print(f"❌ Error: prompts directory not found at {prompts_dir}")
        sys.exit(1)

    # Ensure target directory exists
    prompts_js.parent.mkdir(parents=True, exist_ok=True)

    # Create backup if file exists
    if prompts_js.exists():
        backup_path = prompts_js.with_suffix(".js.bak")
        shutil.copy2(prompts_js, backup_path)
        print(f"✅ Backup created: {backup_path}")

    # Read prompts. Files that do not exist are skipped instead of emitting
    # an empty const — that would leave dead `window.X = X;` references.
    prompts = {}
    for name in PROMPT_NAMES:
        filepath = prompts_dir / f"{name}.txt"
        if filepath.exists():
            prompts[name] = read_prompt_file(filepath)
            print(f"  📄 Read {name}.txt ({len(prompts[name])} chars)")
        else:
            print(f"  ⏭️ Skipping {name}.txt (not present)")

    # Build full file content (overwrite) — only include prompts that exist.
    lines = [
        "// AUTO-GENERATED by sync-prompts.py. Do not edit manually.",
        "// Source: prompts/*.txt",
        "// Context templates used by popup UI.",
        "",
    ]
    for name in PROMPT_NAMES:
        if name not in prompts:
            continue
        const_name = CONST_NAMES[name]
        lines.append(f"const {const_name} = `{prompts[name]}`;")
    lines.append("")
    lines.append("// Expose to window for other scripts")
    for name in PROMPT_NAMES:
        if name not in prompts:
            continue
        const_name = CONST_NAMES[name]
        lines.append(f"window.{const_name} = {const_name};")
    lines.append("")

    content = "\n".join(lines)

    # Write back
    with open(prompts_js, "w", encoding="utf-8") as f:
        f.write(content)

    print("✅ Sync complete!")
    print("")
    print("📝 Changes:")
    for name in PROMPT_NAMES:
        print(f"  - {name}.txt → {CONST_NAMES[name]}")
    print("")
    print("🔄 Remember to reload extension after sync!")


if __name__ == "__main__":
    main()
